<a href="https://colab.research.google.com/github/YifanSong348/STATS302/blob/main/Week%205/HW5_Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from matplotlib import*
import matplotlib.pyplot as plt
from matplotlib.cm import register_cmap
from scipy import stats
from sklearn.decomposition import PCA as sklearnPCA
import seaborn

In [ ]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
  
print("Enter the entries in a single line (separated by space): ")
  
# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix = np.array(entries).reshape(R, C)
print(matrix)

Enter the number of rows:4
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
0 1 2 -1 3 4 0 0 1 2 3 -2
[[ 0  1  2]
 [-1  3  4]
 [ 0  0  1]
 [ 2  3 -2]]


In [ ]:
X = matrix
# mean Centering the data  
X_meaned = X - np.mean(X , axis = 0)
print(X_meaned)

[[-0.25 -0.75  0.75]
 [-1.25  1.25  2.75]
 [-0.25 -1.75 -0.25]
 [ 1.75  1.25 -3.25]]


In [ ]:
# calculating the covariance matrix of the mean-centered data.
cov_mat = np.cov(X_meaned , rowvar = False)
print(cov_mat)

[[ 1.58333333  0.41666667 -3.08333333]
 [ 0.41666667  2.25       -0.25      ]
 [-3.08333333 -0.25        6.25      ]]


In [ ]:
#Calculating Eigenvalues and Eigenvectors of the covariance matrix
eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)
print("values", eigen_values)
print("vectors", eigen_vectors)

values [0.01895337 2.25083921 7.81354076]
vectors [[ 0.89191571  0.07283149 -0.44629805]
 [-0.11764615  0.9903318  -0.07350045]
 [ 0.43663     0.11806145  0.89186083]]


In [ ]:
#sort the eigenvalues in descending order
sorted_index = np.argsort(eigen_values)[::-1]
 
sorted_eigenvalue = eigen_values[sorted_index]
#similarly sort the eigenvectors 
sorted_eigenvectors = eigen_vectors[:,sorted_index]
print(sorted_eigenvalue)
print(sorted_eigenvectors)

[7.81354076 2.25083921 0.01895337]
[[-0.44629805  0.07283149  0.89191571]
 [-0.07350045  0.9903318  -0.11764615]
 [ 0.89186083  0.11806145  0.43663   ]]


In [ ]:
# select the first n eigenvectors, n is desired dimension
# of our final reduced data.
 
n_components = 2 #you can select any number of components.
eigenvector_subset = sorted_eigenvectors[:,0:n_components]
print(eigenvector_subset)

[[-0.44629805  0.07283149]
 [-0.07350045  0.9903318 ]
 [ 0.89186083  0.11806145]]


In [ ]:
#Transform the data 
X2 = np.dot(sorted_eigenvectors.transpose(),X_meaned.transpose()).transpose()
X_reduced = np.dot(eigenvector_subset.transpose(),X_meaned.transpose()).transpose()
print(X_reduced)
print(X2)

[[ 0.83559547 -0.67241063]
 [ 2.91861428  1.47154436]
 [ 0.01723509 -1.78080388]
 [-3.77144483  0.98167015]]
[[ 0.83559547 -0.67241063  0.19272819]
 [ 2.91861428  1.47154436 -0.06121982]
 [ 0.01723509 -1.78080388 -0.12625567]
 [-3.77144483  0.98167015 -0.0052527 ]]
